### ISSUE TITLE
load.rb падает при попытке скачать юзерпик с remotekey

### ISSUE THREAD

**Issue by kappa** [zverok/clio#1]
% ruby bin/load.rb kkapp !!!здесь_remotekey!!!
    /home/kappa/work/clio/vendors/simplehttp.rb:57: #Net::HTTPBadRequest:0xb7766440 : 400 : http://friendfeed-api.com/v2/picture/kkapp?size=large (RuntimeError)
    from /home/kappa/work/clio/vendors/simplehttp.rb:297:in `call'
    from /home/kappa/work/clio/vendors/simplehttp.rb:297:in`handle_response'
    from /home/kappa/work/clio/vendors/simplehttp.rb:323:in `do_http'
    from /home/kappa/work/clio/vendors/simplehttp.rb:388:in`get'
    from /home/kappa/work/clio/lib/frf_client.rb:40:in `raw_request'
    from /home/kappa/work/clio/lib/frf_client.rb:23:in`userpic'
    from /home/kappa/work/clio/lib/frf_client.rb:52:in `extract_feed'
    from bin/load.rb:15

**Comment by kappa** [comment]
Если remotekey не указывать, то вроде бы всё нормально.

**Comment by zverok** [comment]
Спасибо, fixed. Виновата была SimpleHttp (глючная обёртка вокруг Net/HTTP, в котором меня утомляет, что каждое простое действие надо в 10 строчек делать).
