### ISSUE TITLE
падает на индексировании

### ISSUE THREAD

**Issue by mbravorus** [zverok/clio#11]
выглядит так:

23 ноя 21:35:01 INFO: Начато индексирование /Users/mbravo/Sources/clio/result/mbravo
23 ноя 21:35:01 INFO: индексирование /Users/mbravo/Sources/clio/result/mbravo: папки созданы, читаем записи
/Users/mbravo/Sources/clio/vendors/json/common.rb:146:in `encode': "\xD0" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /Users/mbravo/Sources/clio/vendors/json/common.rb:146:in`initialize'
    from /Users/mbravo/Sources/clio/vendors/json/common.rb:146:in `new'
    from /Users/mbravo/Sources/clio/vendors/json/common.rb:146:in`parse'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:172:in `block in run'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in`each'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in `run'
    from bin/clio.rb:103:in`block in <main>'
    from bin/clio.rb:88:in `each'
    from bin/clio.rb:88:in`<main>'

при этом:

pantouflejr:clio mbravo$ ruby --version
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.5.0]

а также при старте говорило:

/Users/mbravo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.

**Comment by zverok** [comment]
Попробуйте стереть vendors/json папку вообще. Теоретически, после этого всё заработает (там локальная копия гема json, для бедных котиков у которых Windows и ничего нельзя поставить банальным gem install json)

**Comment by mbravorus** [comment]
Увы, не помогло

pantouflejr:clio mbravo$ ruby bin/clio.rb -i -u mbravo

# Clio — better Friendfeed backup tool.  by zverok and contributors

25 ноя 01:44:50 INFO: Начато индексирование /Users/mbravo/Sources/clio/result/mbravo
25 ноя 01:44:50 INFO: индексирование /Users/mbravo/Sources/clio/result/mbravo: папки созданы, читаем записи
/Users/mbravo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in `encode': "\xD0" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /Users/mbravo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in`initialize'
    from /Users/mbravo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in `new'
    from /Users/mbravo/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/json/common.rb:148:in`parse'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:172:in `block in run'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in`each'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in `run'
    from bin/clio.rb:103:in`block in <main>'
    from bin/clio.rb:88:in `each'
    from bin/clio.rb:88:in`<main>'

на всякий случай замечу, что попробовал и с другой версией руби, там вышло то же самое:

pantouflejr:clio mbravo$ ruby bin/clio.rb -i -u mbravo

# Clio — better Friendfeed backup tool.  by zverok and contributors

25 ноя 01:42:31 INFO: Начато индексирование /Users/mbravo/Sources/clio/result/mbravo
25 ноя 01:42:31 INFO: индексирование /Users/mbravo/Sources/clio/result/mbravo: папки созданы, читаем записи
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in `encode': "\xD0" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in`initialize'
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in `new'
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in`parse'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:172:in `block in run'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in`each'
    from /Users/mbravo/Sources/clio/lib/indexator.rb:169:in `run'
    from bin/clio.rb:103:in`block in <main>'
    from bin/clio.rb:88:in `each'
    from bin/clio.rb:88:in`<main>'

**Comment by zverok** [comment]
чорт :( ну тогда я не знаю, у меня локально на вашем фиде всё ок, вот, если што, результат: https://dl.dropboxusercontent.com/u/4645221/mbravo-2013-11-24.zip

**Comment by mbravorus** [comment]
Спасибо!

Я тут внимательно вчитался в ошибку, и "все понял". Всего-то надо было корректно у себя объявить локаль.

Если сказать

export LANG=en_US.UTF-8

то потом все отлично работает
