### ISSUE TITLE
Посты сохраняются под именем id+slug, из-за этого при изменении текста поста (и слага) при повторном скачивании появляется дубликат. (-)

### ISSUE THREAD

**Issue by urbansheep** [zverok/clio#12]

**Comment by zverok** [comment]
Эээ это как? При изменении текста поста слаг не меняется же (иначе бы прогорали все ссылки на пост).  Только что создал тестовый пост с текстом «test me», получил урл ..../test-me, поменял текст на «test me too», урл не поменялся.

Или я чего-то не понимаю?

**Comment by zverok** [comment]
А, чорт, таки поменялся, вру. Дурдом какой. 
Кто бы мог предположить.

**Comment by urbansheep** [comment]
Там штука в том, что слаг — опциональная «декоративная» фича, основное — в числовом ID поста, если он есть, урл не побьётся, а слага может и не быть вообще. Клио же сохраняет айтемы со слагом в имени файла, и это приводит как раз к дубликатам.

**Comment by urbansheep** [comment]
Пинг?

**Comment by zverok** [comment]
Почему-то последние 2 ответа (в т.ч. двухмесячной давности) упали на почту только сегодня 0_0, поэтому я об этом таски забыл до твоего поста в фрф. Так чего, можно обозначать как решённое?..

**Comment by urbansheep** [comment]
Думаю, да, я засосал исправление, осталось совместить новьё с остальной набранной базой записей, собственно.
