### ISSUE TITLE
ruby2 compatibility (iconv)

### ISSUE THREAD

**Issue by indeyets** [zverok/clio#13]
clio uses `'iconv'` which is deprecated in 1.9 and seems to be not available in 2.0.

**Comment by indeyets** [comment]
насколько я понимаю, всё дело в замороженых зависимостях.
может их обновить? добавить Gemfile, Gemfile.lock и т.п.

можно даже папку vendor продолжить таскать, но более новую.

или это вызовет какие-то нехорошие последствия?

**Comment by zverok** [comment]
Ну история на самом деле такая, что я пытался собрать такую инсталляцию (ради этого папка vendor), которая бы работала даже на Винде, будучи «просто скачанной». Вообще по нынешним временам можно конечно заигнорить руби 1.8 просто, и настроить всё так, чтобы с 1.9/2.0 работало только. Посмотрю, как это логичнее сделать.

**Comment by zverok** [comment]
ну вроде тупо удаление папки `vendors/json` did the trick. будем ждать разъярённых пользователей :)

**Comment by indeyets** [comment]
:+1: works for me!

(для истории) правка была в этом коммите: 9263cf1
