### ISSUE TITLE
Бьётся кодировка в кириллических хэштегах

### ISSUE THREAD

**Issue by davidmz** [zverok/clio#22]
Win7 64, ruby 2.2.1p85
Вот файл hashtags.js: https://yadi.sk/d/0_9_sW8mfWChX
Выглядит так:
![image](https://cloud.githubusercontent.com/assets/132120/6822755/3dd37f36-d2f3-11e4-8163-e08b65af16f5.png)

**Comment by zverok** [comment]
WTF??? Посмотрю.

**Comment by davidmz** [comment]
Так, я только сейчас обнаружил, что есть clio и есть clio2. Я ставил просто clio, так что, наверное, это не актуальный баг.

**Comment by davidmz** [comment]
Да, в clio2 этого нет. Сорри.
