### ISSUE TITLE
Докапывает до конца, но не останавливается

### ISSUE THREAD

**Issue by kappa** [zverok/clio#8]
28 дек 13:37:52 INFO: Загружено 100 записей, начиная с 9700; дата самой старой — '17 февраля 2009 в 19:21'
28 дек 13:37:57 INFO: Загружено 100 записей, начиная с 9800; дата самой старой — '4 февраля 2009 в 15:31'
28 дек 13:38:05 INFO: Загружено 100 записей, начиная с 9900; дата самой старой — '21 января 2009 в 14:08'
28 дек 13:38:10 INFO: Загружено 100 записей, начиная с 10000; дата самой старой — '2 января 2009 в 23:18'
28 дек 13:38:16 INFO: Загружено 100 записей, начиная с 10100; дата самой старой — '2 января 2009 в 23:18'
28 дек 13:38:21 INFO: Загружено 100 записей, начиная с 10200; дата самой старой — '2 января 2009 в 23:18'
28 дек 13:38:27 INFO: Загружено 100 записей, начиная с 10300; дата самой старой — '2 января 2009 в 23:18'

28 дек 13:38:51 INFO: Загружено 100 записей, начиная с 10400; дата самой старой — '2 января 2009 в 23:18'
28 дек 13:38:57 INFO: Загружено 100 записей, начиная с 10500; дата самой старой — '2 января 2009 в 23:18'
^C^C^C

**Comment by zverok** [comment]
Не могу воспроизвести. Всегда воспроизводится? На фиде любого пользователя? Какое окружение (ОС, версия руби).

**Comment by kappa** [comment]
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux] — последняя Ubuntu.

Попробую воспроизводить на других аккаунтах.

**Comment by kappa** [comment]
На коротких фидах (< 10000 записей) не воспроизвелось.

**Comment by zverok** [comment]
ВНЕЗАПНО воспроизвёл и починил, действительно был тупой баг. 
Так тоже бывает. Полтора года спустя.
