### ISSUE TITLE
Кронджоб-режим для регулярных обновлений

### ISSUE THREAD

**Issue by urbansheep** [zverok/clio#9]
Сейчас даже при использовании отдельных папок создаётся новый дамп на каждый запуск по 10к записей. Но у этого подхода есть проблемы:
1. Скачивание долго работает.
2. Архив фида может быть глубже 10 тысяч.
3. Предыдущие версии дампа могут содержать старые записи за пределами 10к, и в новых версиях их не будет.

Идеальный архив — это все записи из фида на максимальную глубину, с полным индексом тегов и дат.

Для того, чтобы создать такой полный архив, сейчас приходится записи всех дампов (вручную или не очень) копировать в одну большую папку, от старых версий дампов к новым (чтобы обновления постов с комментариями накатывались корректно).

Хочется, чтобы клио при запуске в крон-режиме:
1. Засасывала обновления из фида (обычно 100-200 постов хватает).
2. Сложила их в общую папку.
3. Запустила индексатор.
4. Сделала гзип общей папки сегодняшней датой (или каждый пятый день, или седьмой).
5. Пошла спать до следующего дня.

**Comment by zverok** [comment]
Реализовал ограничение глубины загрузки (передаёшь --depth 100, например, она и загружает только последние 100 записей и складывает их в ту же папку, куда и раньше складывало). Уже на гитхабе.

**Comment by zverok** [comment]
Добавил опцию --zip — если она передана, то вся папка result/имя-фида упаковывается в result/имя-фида-ГГГГ-ММ-ДД.zip

Я правильно понимаю, что эти два изменения закрывают данный issue?

**Comment by urbansheep** [comment]
Спасибо, сейчас скачаю и протестирую.

Если всё работает, то да, этот запрос будет выполнен. )

**Comment by urbansheep** [comment]
Работает, ура!

# Зверёк, спасибо большое!
